### ISSUE TITLE
We Need A PSP Go Details Tutorial

### ISSUE THREAD

**Issue by VisionR1** [khubik2/pysweeper#10]
@khubik2 @zecoxao I'm little confused about psp go, the only new is this https://www.psdevwiki.com/psp/Psp_Go_Jigkick, but this tutorial need a psp go dock n340 and is expensive, and is more cheaper go to a techinian or buy a almost new psp go. Only this with the dock work with psp go?

**Comment by zecoxao** [comment]
Sony Oficial Component Cable have all pins. more news soon...

**Comment by VisionR1** [comment]
> 

Oh understand, i hope for a good solution, keep the good work, you mean this cable?
![50](https://github.com/khubik2/pysweeper/assets/25982450/2edb9f61-fe55-402b-bd41-1eb48ed6241f)

**Comment by VisionR1** [comment]
> Sony Oficial Component Cable have all pins. more news soon...

Oh understand, i hope for a good solution, keep the good work, you mean this cable?
![50](https://github.com/khubik2/pysweeper/assets/25982450/2edb9f61-fe55-402b-bd41-1eb48ed6241f)

**Comment by VisionR1** [comment]
https://www.reddit.com/r/PSP/comments/ptme78/4in1_cable_for_the_psp_go_created/

**Comment by VisionR1** [comment]
@zecoxao is this possible?
![PSP Go fix](https://github.com/khubik2/pysweeper/assets/25982450/c6296f3d-dfc9-429a-86ed-73bbdef55cf3)
![PSP Go fix 1](https://github.com/khubik2/pysweeper/assets/25982450/f9a39077-29b6-462c-aad6-800acc39b8e7)

**Comment by zecoxao** [comment]
you should talk with Peter Lustig. he sells these cables now

**Comment by VisionR1** [comment]
> you should talk with Peter Lustig. he sells these cables now

What cables you mean?

**Comment by zecoxao** [comment]
for psp go and street unbrick

**Comment by VisionR1** [comment]
> for psp go and street unbrick

Understand, i mean what exactly cables? With dock or other? Any image?

**Comment by zecoxao** [comment]
![F48bCHCW0AAbQBL](https://github.com/khubik2/pysweeper/assets/1857828/c8fde993-7016-48d0-ac91-367ded0a9afc)
![F48bCG6WEAAUA86](https://github.com/khubik2/pysweeper/assets/1857828/1e72a7dc-a022-4ef9-8836-d9bf964f4bcd)
![F48bCHiWkAAM0v6](https://github.com/khubik2/pysweeper/assets/1857828/311c85c8-9af9-4eb1-b6a4-3627f8366f78)

**Comment by VisionR1** [comment]
> ![F48bCHCW0AAbQBL](https://user-images.githubusercontent.com/1857828/266846617-c8fde993-7016-48d0-ac91-367ded0a9afc.jpeg) ![F48bCG6WEAAUA86](https://user-images.githubusercontent.com/1857828/266846623-1e72a7dc-a022-4ef9-8836-d9bf964f4bcd.jpeg) ![F48bCHiWkAAM0v6](https://user-images.githubusercontent.com/1857828/266846626-311c85c8-9af9-4eb1-b6a4-3627f8366f78.jpeg)

The last image, i think can make it, just cut my usb and connect it to CP2102 right?

**Comment by VisionR1** [comment]
> ![F48bCHiWkAAM0v6](https://user-images.githubusercontent.com/1857828/266846626-311c85c8-9af9-4eb1-b6a4-3627f8366f78.jpeg)

@zecoxao Thanks for the photos, very useful, the last image for PSP Go, i think can make it, just cut my usb and connect it to CP2102 right? and if you can some info? i mean what color is the 2 cables connect to FT23? what pins?

**Comment by VisionR1** [comment]
@zecoxao Thanks, and i ask what cables is it and any extra info or a tutorial for PSP Go, because in the end of month, i go to buy the cable, but which?

**Comment by zecoxao** [comment]
if you want the go one, you buy the go one :)

**Comment by VisionR1** [comment]
> if you want the go one, you buy the go one :)

Yeah, understand that, but which? The usb or Sony Oficial Component Cable ?

**Comment by VisionR1** [comment]
@zecoxao Yeah, understand that, but which? I mean the normal usb or Sony Oficial Component Cable? because in the end of month, i go to buy the cable, but not have money for both, now i only have all the part and the CP2102. Very helpful if you can provide any tutorial

**Comment by zecoxao** [comment]
contact Peter Lustig on telegram. you can add me there, i'm @zecoxao1

**Comment by VisionR1** [comment]
@zecoxao Thanks. Maybe I'm not clarifying this right, i live in another country, i want make it my self this cable, but i don't know what cable need, the normal usb who also charge the PSP Go or the Sony Oficial Component Cable? now i only have all the part like diode and the CP2102, Very helpful if you can provide any tutorial
![10pcs-lot-usb-charging-cable-data-cable-for-PSP-GO-PSPGO-charger-charging-cable-long-about](https://github.com/khubik2/pysweeper/assets/25982450/ebd2322c-2d7b-48d9-8790-e17ca1f9f5fc)
![262151067-2edb9f61-fe55-402b-bd41-1eb48ed6241f](https://github.com/khubik2/pysweeper/assets/25982450/47ba5b25-88a4-4b2d-b4fd-ab85cdcd5dda)
