### ISSUE TITLE
[HELP] Anyone for PSP Go

### ISSUE THREAD

**Issue by VisionR1** [khubik2/pysweeper#14]
@khubik2 @Yoti @zecoxao 
Because i don't have the FT232RL need it for this and can't get it, i have USB to Serial Module - CP2102, DC-DC Step-Down 1.8-12V 2A - MP2315, 4-channel I2C-safe Bi-directional Logic Level Converter - BSS138 and resist and diode and the non original psp cable, anyone know how can use all this to make it 1.8V need the PSP Go for open the service menu ? Any details tutorial

**Comment by zecoxao** [comment]
buy one from Peter Lustig

**Comment by VisionR1** [comment]
> buy one from Peter Lustig

The same you tell me in the past, if have money to buy it, I wouldn't ask here, and this guy promised a tutorial how to make the cable, something that didn't happen

**Comment by Yoti** [comment]
We all bought 1.8V TTL adapters. Also, you need to disassemble the cable and change pins inside their connector. It isn't very simple procedure.

**Comment by VisionR1** [comment]
> We all bought 1.8V TTL adapters. Also, you need to disassemble the cable and change pins inside their connector. It isn't very simple procedure.

Understand, for that i say if anyone try it with other, can't get 1.8V TTL unfortunately, in this photo i see the head of the cable is untouched and the other side has been cut to connect to TTL

![293697112-c7d65a24-fb2d-4cc3-a41d-992177847878](https://github.com/khubik2/pysweeper/assets/25982450/cdfa6df3-252e-4abb-a8d2-ba7b5b858571)

**Comment by Yoti** [comment]
The cable head is modified as I wrote before. I think work in progress photos was posted somewhere in Twitter.

**Comment by VisionR1** [comment]
> The cable head is modified as I wrote before. I think work in progress photos was posted somewhere in Twitter.

Yeah before 5 months, but now the cable head from the side of psp look untouched or it's so well made it doesn't look like it's been modified
and in case I found 1.8V TTL we need a tutorial how to make it and no one has made, for the pins you said

![293697112-c7d65a24-fb2d-4cc3-a41d-992177847878](https://github.com/khubik2/pysweeper/assets/25982450/d1c5fc1b-b94f-4169-a634-4af776f84093)

**Comment by Yoti** [comment]
Did you check [the Wiki](https://www.psdevwiki.com/psp/Psp_Go_Jigkick) for pinout?

**Comment by VisionR1** [comment]
> Did you check [the Wiki](https://www.psdevwiki.com/psp/Psp_Go_Jigkick) for pinout?

Yeah, i read it, but im not expert like you, if have a tutorial, instructions for how disassemble the cable and change pins inside their connector in psp cable, maybe i can make it, if get a 1.8V TTL like FT232RL, unfortunatly for now can;t get it is not anavable in my country and the only parts i have now is the above i write in first

**Comment by khubik2** [comment]
Ensure a cable has ALL the pins in there by looking inside the connector.
Disassemble the cable head (there should be a seam on the side, use adequate force to break the plastic along the seam)
Expose the board. Use factory-soldered USB cables and trace patterns for guidance.
Odd numbered pins are on the top side and even numbered pins are on the bottom.
![pspgo](https://github.com/khubik2/pysweeper/assets/82090925/d7edfd99-03d0-49c4-bbd8-468a638df898)
If your PSPgo's battery is fine - you don't have to wire pins 20 and 22.
But if it's not, make sure NOT TO USE YOUR TTL ADAPTER'S 5V LINE IF YOU PLAN TO SUPPLY POWER OVER THE CABLE! Adapter's power supply is not capable of powering your PSP alone and you need to wire something in parallel, such as a USB power cable.

Make sure to ground TOH0. Select 1.8 logic level on your adapter. Connect adapter GND to GND, adapter TX to PSP RX and vice versa.
If your adapter is incapable of 1.8V but you know its logic level, you can get away with using a simple resistor voltage divider.
![pspgo](https://github.com/khubik2/pysweeper/assets/82090925/389d5c21-e0c3-41c1-bfa0-887e1c58c972)

**Comment by VisionR1** [comment]
> Ensure a cable has ALL the pins in there by looking inside the connector. Disassemble the cable head (there should be a seam on the side, use adequate force to break the plastic along the seam) Expose the board. Use factory-soldered USB cables and trace patterns for guidance. Odd numbered pins are on the top side and even numbered pins are on the bottom. ![pspgo](https://private-user-images.githubusercontent.com/82090925/300502502-d7edfd99-03d0-49c4-bbd8-468a638df898.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDA5NjgsIm5iZiI6MTcwNjU0MDY2OCwicGF0aCI6Ii84MjA5MDkyNS8zMDA1MDI1MDItZDdlZGZkOTktMDNkMC00OWM0LWJiZDgtNDY4YTYzOGRmODk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE1MDQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNjcxOTA5NDVjNjVmZDQxNjRjZmUwMTZlNTNhN2RiMWM0NzkxMjYxOTgyNGY3OGNlOTI2NjFmYjdkNDdkMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fl67iOL08hXSa3NzmcxDg1hBeLuMH1JSt6cwfm06OII) If your PSPgo's battery is fine - you don't have to wire pins 20 and 22. But if it's not, make sure NOT TO USE YOUR TTL ADAPTER'S 5V LINE IF YOU PLAN TO SUPPLY POWER OVER THE CABLE! Adapter's power supply is not capable of powering your PSP alone and you need to wire something in parallel, such as a USB power cable.
> 
> Make sure to ground TOH0. Select 1.8 logic level on your adapter. Connect adapter GND to GND, adapter TX to PSP RX and vice versa. If your adapter is incapable of 1.8V but you know its logic level, you can get away with using simple resistor dividers on TX and RX lanes. I think you may be able to join them into one-wire bus (aka K-line) with a 1n4148 diode like in PSP-3000 jig assembly to get away with just one voltage divider

Thanks you for this. This is a tutorial

**Comment by VisionR1** [comment]
@khubik2 I try some and i get this

![PSP Go Fix0](https://github.com/khubik2/pysweeper/assets/25982450/1a0a369f-e1a3-42f5-b01d-7841ca7c58de)

![PSP Go Fix](https://github.com/khubik2/pysweeper/assets/25982450/a52d67fc-48eb-4053-a34e-ab9c39f89fb5)

**Comment by zecoxao** [comment]
![image_2024-02-02_23-01-14](https://github.com/khubik2/pysweeper/assets/1857828/e280b432-44d7-4de2-9db8-f90419718b39)
![photo_2024-02-03_11-45-55](https://github.com/khubik2/pysweeper/assets/1857828/b6a385f2-5dbf-43c6-8b62-6626fddd4eda)

**Comment by VisionR1** [comment]
> ![image_2024-02-02_23-01-14](https://private-user-images.githubusercontent.com/1857828/302047162-e280b432-44d7-4de2-9db8-f90419718b39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NzY5NDEsIm5iZiI6MTcwNjk3NjY0MSwicGF0aCI6Ii8xODU3ODI4LzMwMjA0NzE2Mi1lMjgwYjQzMi00NGQ3LTRkZTItOWRiOC1mOTA0MTk3MThiMzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDNUMTYxMDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTAyMjcyYzIzZjkxNzY3ODczNGI4NGU3NDVhYTViNjJjNzc5OTJjNzI1NDQ0NTM4NzI1NDlkNDM5YmEyODhkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t8p7NiM-pG2uW2RIVttUzyjfWwY-L3k_oJ3geXPbaqg) ![photo_2024-02-03_11-45-55](https://private-user-images.githubusercontent.com/1857828/302047165-b6a385f2-5dbf-43c6-8b62-6626fddd4eda.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NzY5NDEsIm5iZiI6MTcwNjk3NjY0MSwicGF0aCI6Ii8xODU3ODI4LzMwMjA0NzE2NS1iNmEzODVmMi01ZGJmLTQzYzYtOGI2Mi02NjI2ZmRkZDRlZGEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDNUMTYxMDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWI2MThjNjg0YTVkZmVhNTk0NGI0ZWM4N2EzODNhMzhiODQ4NTNmYzUzMTE1OTFkNGMzNjBkMGU0YTllNTRmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jVtRDS-Wxw6_oIjiPzf7fu0C6RrqyZ63D3N7E4V0Phs)

Thanks for the images, this help me much, i appreciate
