### ISSUE TITLE
This model psp3000 lose wifi when ark is installed.

### ISSUE THREAD

**Issue by n1ckzero** [khubik2/pysweeper#19]
![WhatsApp Image 2024-06-06 at 13 55 31](https://github.com/khubik2/pysweeper/assets/7030909/fcc30716-74cc-4bc6-ab9c-98cbbfec5beb)

networks settings don't open and browser freezes

Any Solution.

Restoring Nand original fw wifi works.

**Comment by khubik2** [comment]
This is not the repository to submit issues about ARK custom firmware to.
Please address your issues accordingly: https://github.com/PSP-Archive/ARK-4
