### ISSUE TITLE
PSP-3004 - 9C (2 PSP's)

### ISSUE THREAD

**Issue by Sehyn** [khubik2/pysweeper#2]
Hello, so I have been watching your tutorial and decided to give it a try with both of my PSP ending with 9C.
I have zero knowledge on USB TTL - Arduino but following your tutorial seems OK I guess since I'am getting response from the PSP.
I see some are supported some are NOT (9C) .

How do you know if it's supported or not ?

Here is my log: 

5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 02 0D 96
A5 07 06 9D10102814 54
5A 02 08 9B
A5 04 06 E204 6A
5A 02 16 8D
A5 13 06 536F6E79456E6572677944657669636573 6B
5A 0B 80 0D2072C28ABBC07E93 A3
A5 12 06 82D11E642C3E9115F97652736D2A3DD0 85
5A 0A 81 952CA4959A90B94A F3
A5 12 06 D6D6F9331445ABAFDE29F6450365C060 ED
5A 0B 80 045B56D400FF60D7B5 A6
A5 12 06 7FBCEE4A7A61F4D570430FA2208E5588 3C
5A 0A 81 1DF8A545A4BDE05E 7C
A5 12 06 87359D3E063D827091FAE8EC2EA25200 F5
5A 0B 80 976BD639CD8D04385C 17
An exception occurred in IO loop: TypeError("'str' object cannot be interpreted as an integer")

I believe object cannot be interpreted can confirm my 9C is not supported ? Or it can be some other issue?
My PSP has no power led, but has the memory sitck led blinking.

Thank you,

**Comment by khubik2** [comment]
Key has been extracted and added to the script. 85c2d00
