### ISSUE TITLE
PSP GO Info.

### ISSUE THREAD

**Issue by VisionR1** [khubik2/pysweeper#21]
For the PSP GO the info, no need anymore a ttl ? like the FT232RL ?
Because not mentioned in the info.

**Comment by khubik2** [comment]
Yes, it is required.
Communication is still done over TX/RX lines, except this time they're not joined together on PSP side. You don't need a diode anymore.

**Comment by VisionR1** [comment]
> Yes, it is required. Communication is still done over TX/RX lines, except this time they're not joined together on PSP side. You don't need a diode anymore.

Thanks for info.
Is not very clear in the info for PSP Go, that's why I'm asking.
Maybe you should write this.
