### ISSUE TITLE
Did  the key 151 lost in the keys.json 

### ISSUE THREAD

**Issue by kingskyspace** [khubik2/pysweeper#3]
in the keys.json. challenge1_secret  and challenge2_secret contains the 151. but,the keystore no contains 151.did it lost.
5A 0B 80 97BB9312C44CADB431 81
this is the last i reviced from serial port.  151 is i need. 
pls update the keys.json,or provide the documentation.
thanks a lot.

**Comment by Yoti** [comment]
This key was unknown for a long time. Also, both secrets are wrong.

**Comment by khubik2** [comment]
"151" key is the key for 5a 0b 80 97... request.
The secrets were proven wrong and have been redacted after Wildcard discovered the actual key (85c2d00).
