### ISSUE TITLE
Mac/linux compatible issue

### ISSUE THREAD

**Issue by kusazh** [khubik2/pysweeper#4]
Has this script been tested on mac/linux?
I tried this on my Mac and the console printed `5A 01 02 A2 5A0102A25A0102A2...`.

But it succeed on a Windows laptop.

**Comment by khubik2** [comment]
I tested it on Linux, but not on Mac.
I can't set up a Hackintosh machine for testing right now.

**Comment by kusazh** [comment]
Maybe there is a driver issue, thank you!
