### ISSUE TITLE
Stuck at A5 05 06 10C306 76 on PSP-1000

### ISSUE THREAD

**Issue by MerGr** [khubik2/pysweeper#6]
I have a launch model PSP 1000 that I'm trying to debrick, I hooked up the PSP battery pins to a PL2303HXA USB-to-TTL converter and started service, here's the logs : 

`Service started.
Using serial FFFFFFFF
5A 02 01 A2
A5 05 06 10C306 76`

**Comment by Ledoeye** [comment]
I'm having the same issue as you. I bought a lot of 6 PSPs ( **All of em PSP 1001** ) for cheap, managed to fix 4 but the other 2 i can't unbrick. Today i attempted my baryon sweeper setup on a **working psp** and it works perfectly, so my setup is correct. 

The other 2 PSPs when i try to unbrick with sweeper the light changes from blinking orange to steady green light but black screen and I can't do anything. I've spent so much time trying to make this work with these 2 Systems, but i'm at a point where i think the solution might be to just buy an OEM battery and transform it into a Pandora and hopefully it's going to work.

**Comment by ManoDaSilva** [comment]
Got something similar on all my PSP-1000, bricked or not. No matter what I select (autoboot, service or normal), I get this: 
Service started.
Using serial FFFFFFFF
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 00269882E745E5FF75 55
A5 12 06 272167115AF067B5796D82DF004C5FAD 7D
5A 0A 81 8B970E927374348F AE
A5 12 06 7F8F9546FB50E3544AAB5A26F4059E61 6A
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 0046ED0398BD2F89A3 34
A5 12 06 486784D19CD4C6AC1E89EC7FFA216909 BD
5A 0A 81 A06A1AC779518070 75
A5 12 06 4728FB509DA3DD06D712994CCAA5547F 55
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 007BC832D87A46C96A DA
A5 12 06 B4C5B54D9D9F19DD030E51884864CEB1 80
5A 0A 81 853C08DBF525B289 21
A5 12 06 E4D195E2D22277B798ACCBC43CD96012 9A
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 007CF236A93DC6FFCD FE
A5 12 06 ADA4A88B06D77EC15989A9D42E54D829 C0
5A 0A 81 59B559722043E6EF 09
A5 12 06 38E8F7F5AE1ACBA5DA0B003D18F12F35 6F
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 00FB19F04ACEEF70D9 C6
A5 12 06 CFFA0CB0AD340333619E15DF396EFEC9 45
5A 0A 81 2DE93C5DD8BCA4FD 36
A5 12 06 857402AE9EA42D62DD2ED01062685E98 1D
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 00400DF33542921DF7 BD
A5 12 06 DC9D64996806160957E5127126C6FE43 53
5A 0A 81 FB5AB95FDCF9D9FB 04
A5 12 06 D7C3B799555289802EB1549B246B27CA 5A
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 003B91C544EF055072 8F
A5 12 06 A5FBDD4E98EABA749DCEB6D6FE05EDE7 F9
5A 0A 81 A1AEFBB1AD006414 FA
A5 12 06 42E86160FC9F5DEB951C290A82957F51 A9
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 0076E23B144CD860E3 0C
A5 12 06 2A0DA25F3A564D4B3F89DCCE24EE4E47 C9
5A 0A 81 3BFDB7D057FCC49B A9
A5 12 06 CBFF00AFA1F8445220CDD9B33617D91D DE
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 0069C3A48F48677CC4 CC
A5 12 06 DD3F70322B8D789A0BE835987AB4F8E5 EF
5A 0A 81 C3D8D36B35FCBEA1 B1
A5 12 06 02CBBC4BB08F520E414CF1DCFE2F1785 AC
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 00580D3CC6369C49C1 D7
A5 12 06 4B15F5EF671ED7E5DDBC80B528EB7930 33
5A 0A 81 96F1A9A36779FA84 E9
A5 12 06 AB4618BC8DDE8572755730521705B43B C2
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 00E1414F2D5F614DA9 C6
A5 12 06 736E772254A1B55D7C6CB6AC9AB243FC EC
5A 0A 81 DE9199B8059D59F0 6F
A5 12 06 B582FEF0ADD01BDADE4BAA4AFCD64BAC C5
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 00EDD69BB8D0AE0EC0 B8
A5 12 06 2DCCEAEF8DEAE5B213514446B66D5B44 B2
5A 0A 81 B5A727454573BB01 DE
A5 12 06 C52606B1ABDF55D5EBAB45ED10C4CF7C 05
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 002E97F158BAD4F663 25
A5 12 06 E9E9B74D42C7072E29257A0038928B16 FB
5A 0A 81 3B8F21ACCA22F70D 93
A5 12 06 26FA39FD4AC73DD284CCCE6D2E8B74A8 6C
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 0004DF9F1120E8A2D6 07
A5 12 06 9022BBCA2C50D5BF6CA15D1C7350AB5D AA
5A 0A 81 9B7673504D0CA6AB 9C
A5 12 06 2D3FA21F7E01A6171AF332B0048E0F3E 0B
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 00F719D46D2A614FD4 1B
A5 12 06 87F22D03283FE7208C867AC504E3A287 CA
5A 0A 81 0279C46CF9B4D03E B4
A5 12 06 BD5347D479C15E2FC602592D3CD38D28 3E
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 00E555FD5E89F7441C A5
A5 12 06 4D12803139AF3B7CF6954527DF1D8DC4 4F
5A 0A 81 A757DDF9F6CCCC29 8F
A5 12 06 FFA91E352B9D2BF307D65D0D78264083 B9
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 0028279C5E5421176E D7
A5 12 06 5B264725E066019AD5746C3FB17FC060 30
5A 0A 81 F899A596A3256C37 E3
A5 12 06 348219313F14CEE74DF344D2DAA961ED 13
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 001C93E55101419E61 F4
A5 12 06 F53A533F28F2FA16464AC0E071C00A36 B6
5A 0A 81 CFE86AA2E65B63BA F9
A5 12 06 52635C64676242089D31DA85513643C1 02
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 00353459893A2F0A39 23
A5 12 06 474DBFDD19D9B8F49183451495364D30 BF
5A 0A 81 D8D1FF094DF1709A 21
A5 12 06 D062A4E53269E883B04DC995CD67F073 8F
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 006F2813E3CB5A0F8D CC
A5 12 06 A80A9850216D45A915C10C673B6A6065 79
5A 0A 81 2AA527A85EFBFC13 14
A5 12 06 29C0CE8B37A839C6BB2AE2E5EC15FB02 78
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 00CBA3678DA00EEE0F 0D
A5 12 06 59FFB5A44B42E68BA9B1D819EED40125 60
5A 0A 81 C86A0E43C2B14A17 C3
A5 12 06 78A7CB7DC63EF90A6A8CDEA20E8E4A0B 6D
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 004BB7726F064F67C3 B8
A5 12 06 C61EBC98E17D5BE9F9EB4755A0C1578C A4
5A 0A 81 3120D4605F4AAFAC 91
A5 12 06 C9EFF3B281BF11DA5310772C7F49053C AB
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 00DA532315D6E08DCE A4
A5 12 06 BDAECF72CCF839E83EDA411C4F85ADC4 F7
5A 0A 81 43C83CF31A90CB41 2A
A5 12 06 69F9E450835030326B3377BF685A62B1 CE
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 0088C9A7B6D2EF9CC3 4C
A5 12 06 73315BA03CB34F7E66B06142B0B57EAF 9C
5A 0A 81 EAF344E5DB838B47 E4
A5 12 06 3F37FE3C26FE55353A8B038E03249644 8D
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 00FC0D0C4A5B76056E 77
A5 12 06 E125388A7517CCFF7E1B9B44930F0718 EA
5A 0A 81 2DA7B3BFA33E2CDD EA
A5 12 06 99D98292978FD6E6A2ED80DAE1BEF55E FF
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 00E4564EDEB178DBDC D4
A5 12 06 7262E7197269D378F9C46077019A52AB 1C
5A 0A 81 52156B5ACE2F848D E0
A5 12 06 4B76F648EBC8B439A445394ED9A17F32 08
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 004B94F00EB44A6B5E 76
A5 12 06 F38892C7C04C15680B33E0182316B560 61
5A 0A 81 3CA4BA5A3D7EF475 02
A5 12 06 035CFE34E1E4EDCB1DDE15A350C72D54 E9
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 008E7A0A6CC65B8B9F 51
A5 12 06 A141442F3373A143B2230D336D88A7CA E8
5A 0A 81 B5E238FA0E0D7986 37
A5 12 06 B0A3D5B4941FC85F991847106597B282 54
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 002C22449DEC46AA5B B4
A5 12 06 E2A5F0DAAAA6F1BA256CD4D80F7791AA F8
5A 0A 81 81FDE4C0964A9E50 2A
A5 12 06 FB2EAFE803601FA98323563290754864 78
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 003EE0EF008C62FEC1 60
A5 12 06 DAEDBBB3A101F8F9BEAD02253965DF11 5A
5A 0A 81 A8297F989EA32EB6 0D
A5 12 06 F98FF526271732457E16EFBEB6CD00A7 7F
5A 02 01 A2
A5 05 06 10C306 76
5A 02 0C 97
A5 06 06 FFFFFFFF 52
5A 0B 80 00DAF8F0E8898095E0 F2
A5 12 06 AF392FDE8415916CF9BB4E003E01F489 F9
5A 0A 81 181DAE1267BFFF54 AC
A5 12 06 AB01B622309C1FAAAE7956E1BDFE559D 1E

And no reaction from the PSP whatsoever...
