### ISSUE TITLE
PSP Go ? Someone?

### ISSUE THREAD

**Issue by VisionR1** [khubik2/pysweeper#7]
@khubik2 @zecoxao Hi, i try to make some change in my PSP Go (N1004) and mess up with flash0 and flash1 and had brick and show me this now, i press the O but just restart and the same message, you have any solution how to fix it? Can fix it with this tutorial from here?

![249575746-bbe1358a-7fff-4119-8d88-deb39b2d590e](https://github.com/khubik2/pysweeper/assets/25982450/3fe172de-e1d1-4970-8ccf-f30de516fc97)

**Comment by zecoxao** [comment]
not yet. eventually. but not yet

**Comment by VisionR1** [comment]
> 

Understand, i have buy the parts from the screen here, beyond the service menu and fix, can test any other settings with this tool in my psp go? Because nothing working, normal boot, autoboot

**Comment by VisionR1** [comment]
> not yet. eventually. but not yet

Understand, i have buy the parts from the screen here, beyond the service menu and fix, can test any other settings with this tool in my psp go? Because nothing working, normal boot, autoboot

**Comment by zecoxao** [comment]
https://www.psdevwiki.com/psp/Psp_Go_Jigkick (partially implemented)

**Comment by VisionR1** [comment]
> 

Thanks for information, i have buy it the CP2102 and the other parts, now just waiting

**Comment by VisionR1** [comment]
> https://www.psdevwiki.com/psp/Psp_Go_Jigkick (partially implemented)

Thanks for information, i have buy it the CP2102 and the other parts, now just waiting
