### ISSUE TITLE
Trying to reach someone who could help me

### ISSUE THREAD

**Issue by leyed0** [khubik2/pysweeper#9]
Hello. I`m just trying to find someone who could know something about psp  battery eeprom to develop a project.
I am trying to make custom batteries and wanna try to make custom eeproms to get correct percentage and duration info on the psp

**Comment by permafrost06** [comment]
I'm also trying to do the same, unfortunately I don't have any more info to add

**Comment by khubik2** [comment]
Closing as non-issue.
